config/routes.rb
Fbdraft::Application.routes.draw do

  resources :players do
    member do
      post 'assign_roster'
      post 'update_roster'
    end
  end
  resources :teams

  root to: 'dashboard#index'

end

app/models/player.rb
class Player < CouchRest::Model::Base
  include Sunspot::Rails::Searchable

  property :name,       String
  property :team,       String
  property :pos,        String
  property :other_pos,  String
  property :league,     String
  property :norm_sum,   Float
  property :norm_value, Float

  belongs_to :fantasy_team, class_name: "Team"

  timestamps!

  searchable do
    text :name, :team, :pos
  end

  def self.query(string)
    Player.search { fulltext "#{string}" }.results
  end

  def eligible_pos_array
    if self.other_pos.nil?
      other_pos_split = []
    else
      other_pos_split = self.other_pos.split(',').map(&:strip)
    end
    [self.pos] + other_pos_split
  end

  def eligible_pos
    self.eligible_pos_array.join(', ')
  end

  def eligible_pos=(pos_string)
    array = pos_string.split(',').map(&:strip)
    self.update_attributes(pos: array[0], other_pos: array[1..-1].join(', '))
  end

  def eligible_pos_options
    pos_hash = {
      "1B" => ["1B", "CO", "UT"],
      "2B" => ["2B", "MI", "UT"],
      "SS" => ["SS", "MI", "UT"],
      "3B" => ["3B", "CO", "UT"],
      "C"  => ["C",  "UT"],
      "LF" => ["OF", "UT"],
      "CF" => ["OF", "UT"],
      "RF" => ["OF", "UT"],
      "OF" => ["OF", "UT"],
      "UT" => ["UT"],
      "DH" => ["UT"],
      "SP" => ["P"],
      "RP" => ["P"]
    }
    pos_array = self.eligible_pos_array.map { |pos| pos_hash[pos] || ["XX"]}.flatten.uniq + ["R"]
    pos_array.map { |pos| [pos, pos] }
  end

  def roster_spot
    if self.fantasy_team.nil?
      nil
    else
      self.fantasy_team.roster.find { |rs| rs.player_id = self.id }
    end
  end

  def rating(property, mean, stdev)
    value = self.send("proj_#{property}".to_sym).to_f
    ((value - mean.to_f)/stdev.to_f).round(3)
  end

  def self.inherited(subclass)
    super

    subclass.class_eval do

      ###########################################
      # statistics

      def self.proj_view(property, pos=nil)
        view = self.send("by_proj_#{property}".to_sym)
        if pos.nil?
          view
        else
          view.startkey(["#{pos}"]).endkey(["#{pos}",{}])
        end
      end

      def self.values(property, pos=nil)
        self.proj_view(property, pos).values
      end

      def self.avg_stdev(property)
        statistics = self.proj_view(property, nil).reduce.values[0]
        return statistics['mean'], statistics['stdev']
      end

      def self.team_view(team=nil)
        view = self.send("by_team_and_stat".to_sym)
        if team.nil?
          view
        else
          view.startkey(["#{team.id}"]).endkey(["#{team.id}",{}])
        end
      end

      ###########################################
      # views

      design do

          superclass_stats = %w(name team league pos norm_sum)
          subclass_stats = []
          subclass_norms = []
          if subclass.to_s == "Hitter"
            hitter_stats   = HITTER_STATS + ["adj_hits"]
            subclass_stats = hitter_stats.map { |stat| "proj_#{stat}" }
            subclass_norms = HITTER_RATING_STATS.map { |stat| "norm_#{stat}" }
            subclass_array = (HITTER_RATING_STATS + ["h", "ab"]).map { |stat| "'#{stat}'"}.join(', ')
          elsif subclass.to_s == "Pitcher"
            pitcher_stats  = PITCHER_STATS + ["adj_ers", "adj_whs"]
            subclass_stats = pitcher_stats.map { |stat| "proj_#{stat}" }
            subclass_norms = PITCHER_RATING_STATS.map { |stat| "norm_#{stat}" }
            subclass_array = (PITCHER_RATING_STATS + ["er", "walk", "ha", "ip"]).map { |stat| "'#{stat}'"}.join(', ')
          end

          all_stats = superclass_stats + subclass_stats + subclass_norms

          all_stats.each do |stat|
            view "by_#{stat}".to_sym,
              map: "
                function(doc) {
                  if ((doc['type'] == '#{subclass.to_s}') && (doc['#{stat}'] != null)) {
                    strings = ['name', 'team', 'pos', 'league'];
                    if (strings.indexOf('#{stat}') == -1) {
                      value = doc['#{stat}'];
                    } else {
                      value = 1;
                    }
                    emit([doc['pos'], doc['#{stat}']], value);
                  }
                }
              ",
              reduce: "
                function(key, values, rereduce) {
                  if (!rereduce){
                    var count = values.length
                    var mean = sum(values)/count
                    var sumsq = sum(
                                values.map(function(v) {
                                  return v*v
                                })
                               )/count
                    var stdev = Math.sqrt(sumsq-Math.pow(mean,2));

                    return {'mean': mean, 'stdev' : stdev, 'sumsq': sumsq, 'count': count }
                  } else {
                    var count = sum(
                                values.map(function(v){
                                  return v.count
                                 })
                              )
                    var mean = sum(
                                values.map(function(v){
                                  return v.mean * (v.count / count)
                                })
                              )
                    var sumsq = sum(
                                values.map(function(v){
                                  return v.sumsq * (v.count / count)
                                })
                              )
                    var stdev = Math.sqrt(sumsq-Math.pow(mean,2));

                    return {'mean': mean, 'stdev': stdev, 'sumsq': sumsq, 'count': count}
                  }
                }
              "

            view "avail_by_pos_and_#{stat}".to_sym,
              map: "
                function(doc) {
                  if ((doc['type'] == '#{subclass.to_s}') && (doc['#{stat}'] != null) && (doc['fantasy_team_id'] == null)) {
                    if (doc['other_pos'] != '') {
		                  tokens = (doc['pos'] + ', ' + doc['other_pos']).split(/, /);
                    } else {
                      tokens = [doc['pos']];
                    }
                    strings = ['name', 'team', 'pos', 'league'];
                    tokens.map(function(token) {
                      if (strings.indexOf('#{stat}') == -1) {
                        value = doc['#{stat}'];
                      } else {
                        value = tokens.length;
                      }
                      emit([token, doc['#{stat}']], value);
                    });
                  }
                }
              "

            view "avail_by_#{stat}".to_sym,
              map: "
                function(doc) {
                  if ((doc['type'] == '#{subclass.to_s}') && (doc['#{stat}'] != null) && (doc['fantasy_team_id'] == null)) {
                    emit(doc['#{stat}'], 1);
                  }
                }
              "
          end

          view :by_team_and_stat,
            map: "
              function(doc) {
                if ((doc['type'] == '#{subclass.to_s}') && (doc['fantasy_team_id'] != null)) {
                  strings = [#{subclass_array}]
                  for (i in strings) {
                    string = strings[i]
                    emit([doc['fantasy_team_id'], string], doc['proj_' + string]);
                  }
                }
              }
            ",
            reduce: "
              function(key, values, rereduce) {
                return sum(values);
              }
            "


      end

    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_filter :get_player, except: [:index]

  def show
  end

  def index
    if params[:type] == "hitters"
      if params[:pos]
        @players = Hitter.send("avail_by_pos_and_#{sort_column}", startkey: start_key, endkey: end_key, descending: sort_dir).page(params[:page])
      else
        @players = Hitter.send("avail_by_#{sort_column}", descending: sort_dir).page(params[:page])
      end

    elsif params[:type] == "pitchers"
      if params[:pos]
        @players = Pitcher.send("avail_by_pos_and_#{sort_column}", startkey: start_key, endkey: end_key, descending: sort_dir).page(params[:page])
      else
        @players = Pitcher.send("avail_by_#{sort_column}", descending: sort_dir).page(params[:page])
      end

    elsif params[:q]
      @players = Player.query(params[:q])
      render "search_results"
    else
      @players = []
    end
  end

  def edit
  end

  def update
    if params[:hitter]
      @player.update_attributes(params[:hitter])
    elsif params[:pitcher]
      @player.update_attributes(params[:pitcher])
    end

    redirect_to action: "show", id: @player.id
  end

  def assign_roster
    team = Team.find(params[:roster_spot]["fantasy_team_id"])

    @player.update_attributes(fantasy_team: team)

    name = @player.name
    rs = RosterSpot.new(position:         params[:roster_spot]["position"],
                        salary:           params[:roster_spot]["salary"],
                        contract:         params[:roster_spot]["contract"],
                        name:             name,
                        player_id:        params[:id],
                        fantasy_team_id:  team.id)
    team.roster << rs
    if team.save
      team.update_proj_totals
      Team.update_proj_rank
      redirect_to team_path(team)
    else
      redirect_to action: "show", id: params[:id]
    end
  end

  def update_roster
    team = Team.find(params[:roster_spot]["fantasy_team_id"])

    current_team = @player.fantasy_team
    rs = current_team.roster.find{ |rs| rs.player_id = params[:id] }
    current_team.roster.delete(rs)
    current_team.save

    @player.update_attributes(fantasy_team: team)

    unless team.nil?
      name = @player.name
      rs = RosterSpot.new(position:         params[:roster_spot]["position"],
                          salary:           params[:roster_spot]["salary"],
                          contract:         params[:roster_spot]["contract"],
                          name:             name,
                          player_id:        params[:id],
                          fantasy_team_id:  team.id)
      team.roster << rs
      if team.save
        team.update_proj_totals
        Team.update_proj_rank
        redirect_to team_path(team)
      else
        redirect_to action: "show", id: params[:id]
      end
    else
      redirect_to action: "show", id: params[:id]
    end
  end

  private

  def get_player
    @player = Player.find(params[:id])
  end

  def sort_column
    params[:sort].nil? ? "norm_sum" : params[:sort]
  end

  def sort_dir
    asc_sort_params = %w(name team pos proj_era proj_whip)
    asc_sort_params.include?(params[:sort]) ? false : true
  end

  def start_key
    asc_sort_params = %w(name team pos proj_era proj_whip)
    asc_sort_params.include?(params[:sort]) ? [params[:pos]] : [params[:pos], {}]
  end

  def end_key
    asc_sort_params = %w(name team pos proj_era proj_whip)
    asc_sort_params.include?(params[:sort]) ? [params[:pos], {}] : [params[:pos]]
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_playertable.html.haml
-#This partial relies on the following locals:
-#  players: an array of @player objects
-#  type:    a string key to be used for hash keying as well as sorting

- column_hash = { hitters: Hash[HITTER_LABELS.zip(HITTER_STATS)], pitchers: Hash[PITCHER_LABELS.zip(PITCHER_STATS)] }
- rating_hash = { hitters: HITTER_RATING_STATS, pitchers: PITCHER_RATING_STATS }
- ratio_hash = { hitters: [1000.0, 3, "avg", "slg", "obp"], pitchers: [100.0, 2, "era", "whip", "k9", "bb9"]}

- key = type.try(:to_sym)

- columns = column_hash[key]
- ratings = rating_hash[key]
- ratios = ratio_hash[key]

%table.table.table-condensed
  %tr
    %th= link_to "Name", type: type, pos: pos, sort: "name"
    %th= link_to "Team", type: type, pos: pos, sort: "team"
    %th= link_to "Pos", type: type, pos: pos, sort: "pos"

    - columns.each do |label, stat|
      %th{width: "45"}= link_to label, type: type, pos: pos, sort: "proj_#{stat}"

    %th= link_to "$", type: type, pos: pos

  - players.each do |player|
    %tr
      %td= link_to player.name, player_path(player)
      %td= player.team
      %td= player.eligible_pos

      - columns.each do |label, stat|
        - proj = player.send("proj_#{stat}".to_sym)
        - if ratios.include?(stat)
          - proj = sprintf("%.#{ratios[1]}f",proj/ratios[0])

        - if ratings.include?(stat)
          %td{style: "border: 1px dotted"}
            - norm = player.send("norm_#{stat}".to_sym)
            %abbr{title: norm}= proj
        - else
          %td{style: "color: #bbbbbb"}
            = proj

      %td{style: "border: 1px dotted"}
        %abbr{title: player.norm_sum}
          %em= player.norm_value.round(0)

- if players.length > 1
  = paginate players

app/views/players/_roster_spot.html.haml
= form_tag({ action: action }, class: "well form-inline" ) do
  = label_tag "Salary"
  = text_field        :roster_spot, :contract, value: roster_spot.contract, class: "span1"
  %div.input-prepend
    <span class="add-on">$</span>#{text_field :roster_spot, :salary, value: roster_spot.salary, class: "span1"}
  = select            :roster_spot, :position, player.eligible_pos_options, { selected: roster_spot.position }, { class: "span1" }
  = collection_select :roster_spot, :fantasy_team_id, Team.all, :id, :owner, { include_blank: true, selected: roster_spot.fantasy_team_id }
  = submit_tag "Assign Player", class: "btn"

app/views/players/edit.html.haml
%h1= @player.name

= form_for @player, url: player_path(@player) do |f|
  = f.label :name
  = f.text_field :name
  = f.label :team
  = f.text_field :team
  = f.label :pos
  = f.text_field :eligible_pos
  = f.submit "Update Player"

app/views/players/index.html.haml
= render "shared/navigation"

- unless @players.blank?
  %h1= params[:type].try(:titleize)

  = render partial: "playertable", locals: { players: @players, type: params[:type], pos: params[:pos] }

app/views/players/search_results.html.haml
= render "shared/navigation"

%h3 Search Results

%ul
  - @players.each do |player|
    %li
      = link_to player.name, player_path(player)
      &nbsp;
      %em
        = player.pos
        (#{player.team})
      %strong
        - unless player.fantasy_team.nil?
          = link_to player.fantasy_team.name, team_path(player.fantasy_team)

= render "shared/footer"

app/views/players/show.html.haml
%h3= @player.name

= render partial: "playertable", locals: { players: [@player], type: @player.class.to_s.tableize, pos: nil }

%hr
%p
  - if @player.fantasy_team.nil?
    = render partial: "roster_spot", locals: { roster_spot: RosterSpot.new(contract: "A", salary: "1", fantasy_team_id: nil),
                                               player: @player,
                                               action: "assign_roster" }
  - else
    %em Already on #{@player.fantasy_team.owner}'s team
    = render partial: "roster_spot", locals: { roster_spot: @player.roster_spot,
                                               player: @player,
                                               action: "update_roster" }